#!/usr/bin/env python

import os
import json
from ast import literal_eval
#import sys
#from time import sleep
#from timeout import timeout

from config0_publisher.loggerly import Config0Logger
from config0_publisher.resource.manage import ResourceCmdHelper
from config0_publisher.serialization import b64_decode
from config0_publisher.serialization import b64_encode

#from config0_publisher.resource.manage import to_jsonfile
#from config0_publisher.cloud.aws.codebuild import CodebuildResourceHelper

class Config0ResourceTFVars(object):
    """

    This class serves as an interface for interacting with Terraform, providing variables, inputs, and outputs.
    It is a specific implementation of TFVars on the Config0 platform.

    Attributes:
        resource_settings (dict):
          A dictionary of resource settings that include most of the settings/variables for interacting with Terraform.
          The resource settings are retrieved from the environment variable CONFIG0_RESOURCE_SETTINGS_HASH, which is base64 encoded

        resource_values (dict):
          A dictionary of "resource" values to insert into the database.
          It allows Terraform infrastructures values to be queried, retrieved, and used in other Config0 Terraform imported templates.

        tf_configs (dict): A dictionary of Terraform settings retrieved from resource_settings.
        tf_exec_skip_keys (list): A list of keys to skip when converting Terraform state files to resources values (insert into database)
        tf_output_skip_keys (list): A list of output keys to skip when converting Terraform state files to resources values (insert into database).
        tf_exec_include_raw (bool): A flag indicating whether to include the raw Terraform state file in resources values (insert into database).
        tf_exec_add_keys (list): A list of keys to explicitly include when converting Terraform state files to resources values (insert into database).
        tf_exec_remove_keys (list): A list of keys to exclude/remove when converting Terraform state files to resources values (insert into database).
        do_not_display (list): A list of keys not to display when converting Terraform state files to resources values (insert into database).
        tf_exec_map_keys (dict): A dictionary of keys to map when converting Terraform state files to resources values (insert into database).
        tf_exec_state_file (str): The Terraform state file path.
        tf_runtime (dict):
           A dictionary of runtime settings retrieved from resource_settings.
           This includes settings like the environment variables when executing terraform
        resource_labels (dict):
           A dictionary of resource labels (to be queried) to insert with the resource values.
           This is similar to Kubernetes labels
        resource_type (str): The resource type.
        provider (str):
           The provider.
           Examples include: Config0, aws, do (digital ocean)
    """

    def __init__(self):

        self.classname = "Config0ResourceTFVars"

        self.tf_configs = {}

        self.tf_exec_skip_keys = [
            "sensitive_attributes",
            "ses_smtp_password_v4",
        ]

        self.tf_output_skip_keys = [
            "tags",
            "label",
            "tag",
            "_id",
            "resource_type",
            "provider",
            "labels",
        ]

        self.tf_exec_include_raw = None
        self.tf_exec_add_keys = []

        self.tf_exec_remove_keys = [
            "private",
            "secret",
        ]

        self.do_not_display = [
            "AWS_SECRET_ACCESS_KEY",
            "secret",
        ]

        self.tf_exec_map_keys = {}

        self.tf_exec_state_file = os.environ.get("TF_EXEC_STATE_FILE",
                                                 "terraform-tfstate")

        self.add_resource_inputargs = {}

        self.std_labels_keys = [
            "region",
            "provider",
            "source_method",
            "resource_type",
        ]

        # set terraform settings
        self._set_tf_configs()

    # only use for creation
    def _set_tf_configs(self):
        """
        This method sets the Terraform settings.
        """
        try:
            self.tf_configs = self.runtime_exec["tf_configs"]
        except:
            self.tf_configs = {}

        if not self.tf_configs:
            return

        self.terraform_type = self.tf_configs.get("terraform_type")

        # ResourceCmdHelper is not terraform aware
        # so we map it resource accordingly
        if self.tf_configs.get("tf_exec_postscript_path"):
            self.postscript_path = self.tf_configs["tf_exec_postscript_path"]
        elif self.tf_configs.get("tf_exec_postscript"):
            self.postscript = self.tf_configs["tf_exec_postscript"]

    def _get_tfstate_file(self):
        """
        This method gets the Terraform state file.
        """

        if not os.path.exists(self.tf_exec_state_file):
            self.logger.debug(f'terraform state file to parse does not exists: {self.tf_exec_state_file}')
            return

        # read output file
        with open(self.tf_exec_state_file) as json_file:
            data = json.load(json_file)

        if not data:
            msg = "tfstate_to_output: there is no data from {}".format(os.path.join(os.getcwd(),
                                                                                    self.tf_exec_state_file))
            self.logger.debug(msg)

            return

        return data

    def _insert_resource_values(self, values):
        """
        This method inserts the resource values into the output values.
        """
        if not self.resource_values:
            return

        for _k, _v in self.resource_values.items():
            self.logger.debug(
                f"resource values: key \"{_k}\" -> value \"{_v}\""
            )
            values[_k] = _v

    # duplicate wertqttetqwetwqtqwt
    def _insert_standard_resource_labels(self,values):

        for key in self.std_labels_keys:

            if not values.get(key):
                self.logger.debug('source standard label key "{}" not found'.format(key))
                continue

            label_key = "label-{}".format(key)

            if values.get(label_key):
                self.logger.debug('label key "{}" already found'.format(label_key))
                continue

            values[label_key] = values[key]

    def _insert_resource_labels(self,values):

        if not self.resource_labels: 
            return

        for _k,_v in self.resource_labels.items():
            self.logger.debug(f'resource labels: key "{"label-{}".format(_k)}" -> value "{_v}"')
            values["label-{}".format(_k)] = _v

    def _insert_tf_outputs(self,values):
    
        try:
            outputs = self.data["outputs"]
        except:
            outputs = None

        if not outputs: 
            return

        # put outputs in 
        for k,v in outputs.items():
    
            # skip certain keys
            if k in self.tf_output_skip_keys:
                continue

            # already set and exists
            if values.get(k):
                continue
    
            values[k] = v['value']

    def _insert_tf_raw(self,values):
        
        if not self.tf_exec_include_raw:
            return

        if self.data:
            data = self.data
        else:
            data = self._get_tfstate_file()

        self.logger.debug("include raw = True")

        values["raw"] = {"terraform":b64_encode(data)}

    def _insert_tf_add_keys(self,values):

        for resource in self.data["resources"]:
    
            if resource["type"] != self.terraform_type:
                continue

            self.logger.debug("-" * 32)
            self.logger.debug("instance attribute keys")
            self.logger.debug(list(resource["instances"][0]["attributes"].keys()))
            self.logger.debug("-" * 32)

            for instance in resource["instances"]:

                for _key,_value in resource["instances"][0]["attributes"].items():
    
                    if not _value:
                        continue

                    if _key in values: 
                        continue

                    if _key in self.tf_exec_skip_keys:
                        self.logger.debug('tf_exec_skip_keys: tf instance attribute key "{}" skipped'.format(_key))
                        continue
    
                    # we add if tf_exec_add_key not set, all, or key is in it 
                    if not self.tf_exec_add_keys:
                        _added_bc = "tf_exec_add_keys=None"
                    elif self.tf_exec_add_keys == "all":
                        _added_bc = "tf_exec_add_keys=all"
                    elif _key in self.tf_exec_add_keys:
                        _added_bc = "tf_exec_add_keys/key{} found".format(_key)
                    else:
                        _added_bc = None

                    if not _added_bc:
                        self.logger.debug("tf_exec_add_keys: key {} skipped".format(_key))
                        continue

                    self.logger.debug('{}: tf key "{}" -> value "{}" added to resource values'.format(_added_bc,
                                                                                                      _key,
                                                                                                      _value))

                    if isinstance(_value,list):
                        try:
                            values[_key] = ",".join(_value)
                        except:
                            values[_key] = _value
                    elif isinstance(_value,dict):
                        try:
                            values[_key] = json.dumps(_value)
                        except:
                            values[_key] = _value
                    else:
                        values[_key] = _value
                break

    def _insert_tf_remove_keys(self,values):

        if not self.tf_exec_remove_keys:
            return

        self.add_resource_inputargs["remove_keys"] = self.tf_exec_remove_keys
        self.add_resource_inputargs["encrypt_fields"] = [ "raw" ]  # raw is appended to encrypted fields

        return 

    def _insert_tf_map_keys(self,values):

        self.logger.debug("#"*32)
        self.logger.debug("tfstate_to_output: tf_exec_map_keys")
        self.logger.json(self.tf_exec_map_keys)
        self.logger.debug("#"*32)

        if not self.tf_exec_map_keys:
            return

        for _insertkey,_refkey in self.tf_exec_map_keys.items():

            '''
            # _insertkey = "p1"
            # _refkey = "q1"

            # _insertkey = values
            # _refkey = {"a":"b","c":"d"}
            # values["values"]["a"] = values["b"]
            '''

            if values.get(_insertkey):
                self.logger.warn("mapped key {} already exists - clobbering".format(_insertkey))
                #continue
    
            # see if _refkey is a subkey
            if isinstance(_refkey,dict):

                if not values.get(_insertkey):
                    values[_insertkey] = {}
    
                for _sub_insertkey,_sub_refkey in _refkey.items():

                    if not values.get(_sub_refkey):
                        self.logger.debug('mapped key sub_insertkey {} sub_refkey {} not found'.format(_sub_insertkey,
                                                                                                       _sub_refkey))
                    # revisit 432523543245
                    # ref 432523543245
                    # do we want to nest 2 levels deep?
                    if "," in values[_sub_refkey]:
                        _sub_insertkey2,_subrefkey2 = values[_sub_refkey].split(",")

                        if _sub_insertkey2 not in self.do_not_display:
                            self.logger.debug('mapped key ["{}"]["{}"]["{}"] -> value "{}"'.format(_insertkey,
                                                                                                   _sub_insertkey,
                                                                                                   _sub_insertkey2,
                                                                                                   values[_sub_refkey.strip()][_subrefkey2.strip()]))

                        values[_insertkey][_sub_insertkey] = values[_sub_refkey.strip()][_subrefkey2.strip()]

                    else:
                        if _sub_insertkey not in self.do_not_display:
                            self.logger.debug('mapped key ["{}"]["{}"] -> value "{}"'.format(_insertkey,
                                                                                             _sub_insertkey,
                                                                                             values[_sub_refkey.strip()]))

                        values[_insertkey][_sub_insertkey] = values[_sub_refkey]
    
            elif values.get(_refkey):
                if _refkey not in self.do_not_display:
                    self.logger.debug('mapped key ["{}"] -> value "{}"'.format(_insertkey,_refkey))

                values[_insertkey] = values[_refkey]

            elif not values.get(_refkey):
                self.logger.warn('mapped key not found insertkey "{}" refkey "{}"'.format(_insertkey,
                                                                                          _refkey))

    def _tfstate_to_output(self):
        
        self.data = self._get_tfstate_file()

        if not self.data:
            self.logger.debug("u4324: no data to retrieved from statefile")
            return False

        self.logger.debug("u4324: retrieved data from statefile")

        values = { "terraform_type":self.terraform_type,
                   "resource_type":self.resource_type,
                   "source_method":"terraform",
                   "provider":self.provider,
                   "main":True }
        
        self._insert_resource_values(values)

        # special case of ssm_name/secrets
        if self.ssm_name:
            values["ssm_name"] = self.ssm_name

        try:
            self._insert_resource_labels(values)
        except:
            self.logger.warn("_insert_resource_labels failed")

        try:
            self._insert_tf_raw(values)
        except:
            self.logger.warn("_insert_tf_raw b64 failed")

        try:
            self._insert_tf_outputs(values)
        except:
            self.logger.warn("_insert_tf_outputs failed")

        try:
            self._insert_tf_add_keys(values)
        except:
            self.logger.warn("_insert_tf_add_keys failed")

        try:
            self._insert_tf_map_keys(values)
        except:
            self.logger.warn("_insert_tf_map_keys failed")

        try:
            self._insert_standard_resource_labels(values)
        except:
            self.logger.warn("_insert_standard resource labels failed")

        try:
            self._insert_tf_remove_keys(values)
        except:
            self.logger.warn("_insert_tf remove keys failed")

        return values
        
class Main(ResourceCmdHelper,Config0ResourceTFVars):

    def __init__(self):

        '''

        # ref 4353245325
        #self.shelloutconfig = "config0-publish:::{}::resource_wrapper".format(self.app_name)

        '''

        self.classname = 'TerraformWrapper'

        self.logger = Config0Logger(self.classname,
                                    logcategory="cloudprovider")

        self.logger.debug("Instantiating %s" % self.classname)

        self.postscript = None
        self.postscript_path = None
        self.runtime_env_vars = None
        self.exclude_tfvars = []
        self.build_env_vars = {}

        self.bool_none = [ "None",
                           "none",
                           "null",
                           "NONE",
                           "None",
                           None ]

        self.bool_false = [ "false",
                            "False",
                            "FALSE",
                            False ]

        self.bool_true = [ "TRUE",
                           "true",
                           "True",
                           True ]

        self.resource_values = None
        self.resource_labels = None
        self.resource_type = None
        self.provider = None

        self.method = os.environ.get("METHOD",
                                     "create")

        self.use_remote_state = os.environ.get("USE_REMOTE_STATE",
                                               True)

        # set config0 resource settings
        # env var CONFIG0_RESOURCE_SETTINGS_HASH/config0_resource_settings_hash
        self._init_config0_resource_settings()

        # parses env var CONFIG0_RESOURCE_SETTINGS_HASH/config0_resource_settings_hash
        # sets things like method, phases_params, etc
        Config0ResourceTFVars.__init__(self)

        set_must_exists = [
            "tmp_bucket",
            "log_bucket"
        ]

        if self.method == "create":
            set_must_exists.extend( [
                "ssm_name",
                "stateful_id",
                "remote_stateful_bucket"
            ] )

        # ref 4353245325
        ResourceCmdHelper.__init__(
            self,
            main_env_var_key="CONFIG0_RUNTIME_EXEC_HASH",
            app_name="terraform",
            set_must_exists=set_must_exists,
            set_default_values={
               "failed_destroy": None,
               "ssm_name": None
            }
        )

        self.terraform_tfvars = os.path.join(self.exec_dir,
                                             "terraform.tfvars")

        self.tf_results = None

        # phase configuration must come after
        # ResourceCmdHelper
        self.set_cur_phase()

    # only use for creation
    def _set_runtime_settings(self):
        """
        This method sets the runtime settings.
        """

        self.runtime_env_vars = {}

        try:
            env_vars = self.runtime_exec.get("env_vars")  # ref 4532643623642
        except:
            env_vars = None

        if not env_vars:
            return

        for _k, _v in env_vars.items():
            self.runtime_env_vars[_k.upper()] = _v

    def _init_config0_resource_settings(self):
        """
        This method initializes the Config0 resource settings.
        """

        try:
            _settings = b64_decode(os.environ.get("CONFIG0_RESOURCE_SETTINGS_HASH"))
        except:
            _settings = {}  # probably destroy

        if not _settings:
            return

        resource_exec_hash = _settings.get("resource_exec_hash")
        runtime_exec_hash  = _settings.get("runtime_exec_hash")
        common_exec_hash  = _settings.get("common_exec_hash")

        if resource_exec_hash:
            os.environ["CONFIG0_RESOURCE_EXEC_HASH"] = resource_exec_hash
            self.resource_exec = b64_decode(resource_exec_hash)

        if runtime_exec_hash:
            os.environ["CONFIG0_RUNTIME_EXEC_HASH"] = runtime_exec_hash
            self.runtime_exec = b64_decode(runtime_exec_hash)

        if common_exec_hash:
            os.environ["CONFIG0_COMMON_EXEC_HASH"] = common_exec_hash
            #common_exec = b64_decode(common_exec_hash)

        self.provider = self.resource_exec.get("provider")
        self.resource_type = self.resource_exec.get("type")
        self.resource_values = self.resource_exec.get("values")
        self.resource_labels = self.resource_exec.get("labels")

        if not self.resource_type:
            raise Exception("resource_type needs to be set")

        if not self.provider:
            self.logger.error("provider should be set")

        # sets things like stateful_id and ssm_name
        # as environment variables
        self._set_runtime_settings()

        return True

    def _set_build_method(self):

        if os.environ.get("USE_CODEBUILD"):  # longer than 900 seconds
            self.build_method = "codebuild"
        elif os.environ.get("USE_LAMBDA"):  # shorter than 900 seconds
            self.build_method = "lambda"
        elif os.environ.get("USE_AWS",True):  # select codebuild or lambda
            if self.build_timeout > 900:
                self.build_method = "codebuild"
            else:
                self.build_method = "lambda"
        else:
            self.build_method = "local"

    def add_destroy_params(self,resource):

        '''
        - we typically load the destroy parameters along with created resource like a
        VPC or database 

        - the resource is therefore self contained, whereby it specifies to the
        system how it can be destroyed.

        - for terraform, we include things like the docker image used to
        destroy the resource and any environmental variables 
        '''

        # Create destroy resource arguments and reference
        resource["destroy"] = {"shelloutconfig":self.shelloutconfig}

        # environmental variables to include during destruction
        env_vars = {
            "DOCKER_EXEC_ENV": self.docker_image,
            "DOCKER_RUNTIME": self.docker_image,
            "REMOTE_STATEFUL_BUCKET":self.remote_stateful_bucket,
            "STATEFUL_ID": self.stateful_id,
            "BUILD_TIMEOUT": self.build_timeout,
            "APP_DIR":self.app_dir,
            "METHOD": "destroy"
        }

        if self.destroy_env_vars: 
            env_vars = dict(env_vars,
                            **self.destroy_env_vars)

        resource["destroy"]["env_vars"] = json.dumps(env_vars)

        if env_vars.get("STATEFUL_ID"): 
            resource["destroy"]["stateful_id"] = env_vars["STATEFUL_ID"]

        if self.destroy_execgroup: 
            resource["destroy"]["execgroup"] = self.destroy_execgroup

        return resource

    def _get_runtime_env_vars(self,method="create"):

        if not self.build_env_vars:
            self.build_env_vars = {}

        if method == "create":
            try:
                exclude_vars = list(self.tf_configs["tf_vars"].keys())
            except:
                exclude_vars = self.exclude_tfvars

            self.insert_os_env_prefix_envs(self.build_env_vars,
                                           exclude_vars)

            self.build_env_vars["SHARE_DIR"] = self.share_dir # this should be set by ResourceCmdHelper
            self.build_env_vars["RUN_SHARE_DIR"] = self.run_share_dir # this should be set by ResourceCmdHelper
            self.build_env_vars["LOG_BUCKET"] = self.log_bucket # this should be set by ResourceCmdHelper
            self.build_env_vars["TMP_BUCKET"] = self.tmp_bucket # this should be set by ResourceCmdHelper
            self.build_env_vars["BUILD_TIMEOUT"] = self.build_timeout # this should be set by ResourceCmdHelper and used for duratiion of temp iam credentials
            self.build_env_vars["DOCKER_IMAGE"] = self.docker_image

            if self.runtime_env_vars:
                for _k,_v in self.runtime_env_vars.items():
                    self.build_env_vars[_k] = _v

        self.build_env_vars["STATEFUL_ID"] = self.stateful_id # this should be set by ResourceCmdHelper
        self.build_env_vars["APP_DIR"] = self.app_dir  # this should be set by ResourceCmdHelper
        self.build_env_vars["APP_NAME"] = self.app_name  # this should be set by ResourceCmdHelper
        self.build_env_vars["REMOTE_STATEFUL_BUCKET"] = self.remote_stateful_bucket # this should be set by ResourceCmdHelper
        self.build_env_vars["TMPDIR"] = "/tmp"

        # ssm name setting
        if self.build_env_vars.get("SSM_NAME"):     # usually set in create
            self.ssm_name = self.build_env_vars["SSM_NAME"]
        elif os.environ.get("SSM_NAME"):
            self.ssm_name = os.environ["SSM_NAME"]

        if self.ssm_name:
            self.build_env_vars["SSM_NAME"] = self.ssm_name

        return 

    def _aggregate_output(self,results,output=None):

        if not output:
            output = ""

        if not results:
            return output

        try:
            _output = results.get("output")
        except:
            _output = None

        if not _output:
            return output

        return output + results.get("output")

    def _tf_map_list_fix_value(self,_value):

        # check object type
        # convert to string
        if isinstance(_value,dict):
            _value = json.dumps(_value)

        if isinstance(_value,list):
            _value = json.dumps(_value)

        # check if string object is a list or dict
        _map_list_prefixes = ["[","{"]
        _map_list_suffixes = ["]","}"]

        _status = None

        try:
            _first_char = _value[0]
        except:
            _first_char = None

        if not _first_char:
            msg = "cannot determine first character for _value {} type {}".format(_value,
                                                                                  type(_value))

            raise Exception(msg)

        if _value[0] not in _map_list_prefixes: 
            return _value,_status

        # map or list?
        _status = True
        _value = _value.replace("'",'"')

        if _value[0] not in _map_list_prefixes and _value[0] in ["'",'"']:

            msg = "the first character should be {}".format(_map_list_prefixes)
            raise Exception(msg)

        if _value[-1] not in _map_list_suffixes and _value[-1] in ["'",'"']:

            msg = "the last character should be {}".format(_map_list_suffixes)
            raise Exception(msg)

        return _value,_status

    def _tf_number_value(self,value):

        try:
            value0 = value[0]
        except:
            value0 = None

        if value0 and value0 in [ "0", 0 ]:
            return 0,False

        if "." in str(value):

            try:
                new_value = float(value)
                return new_value,"float"
            except:
                pass

        else:

            try:
                new_value = int(value)
                return new_value,"int"
            except:
                pass
    
        return value,None

    def _convert_iter_to_str(self,obj):

        if isinstance(obj,list) or isinstance(obj,dict):
            try:
                new_obj = json.dumps(literal_eval(json.dumps(obj)))
            except:
                new_obj = json.dumps(obj).replace("'",'"')

            return new_obj

        try:
            new_obj = json.dumps(literal_eval(obj))
        except:
            new_obj = obj

        return new_obj

    def _get_bool_tf_var(self,value):

        if value in self.bool_none:
            return 'null'

        if value in self.bool_false:
            return 'false'

        if value in self.bool_true:
            return 'true'

        return value

    # revisit 4352525
    # create terraform.tfvars file from TF_VAR_* variables
    def _create_terraform_tfvars(self):

        if self.tf_configs and self.tf_configs.get("tf_vars"):
            _tfvars = self.tf_configs["tf_vars"]
        else:
            _tfvars = self.get_os_env_prefix_envs()

        if not _tfvars: 
            return

        with open(self.terraform_tfvars,"w") as f:

            for _key,_input in _tfvars.items():
                _type = _input["type"]

                if _type == "dict":
                    _value = self._convert_iter_to_str(_input["value"])
                    _quoted = None
                elif _type == "list":
                    _value = self._convert_iter_to_str(_input["value"])
                    _quoted = None
                elif _type == "bool":
                    _quoted = None
                    _value = self._get_bool_tf_var(_input["value"])
                elif _type == "float":
                    _value = _input["value"]
                    _quoted = None
                elif _type == "int":
                    _value = _input["value"]
                    _quoted = None
                else:
                    _value = _input["value"]
                    _quoted = True

                self.logger.debug("_create_terraform_tfvars (new_format): {} -> <{}> {}".format(_key,
                                                                                                _type,
                                                                                                _value))

                if _quoted:
                    _entry = '{} \t= "{}"'.format(_key,_value)
                else:
                    _entry = '{} \t= {}'.format(_key,_value)

                f.write(_entry)
                f.write("\n")

        self.logger.debug("*"*32)
        self.logger.debug("")
        self.logger.debug("Wrote terraform.tfvars: {}".format(self.terraform_tfvars))
        self.logger.debug("")
        self.logger.debug("*"*32)

        return _tfvars.keys()

    def _exec_tf_apply(self):

        self._get_runtime_env_vars(method="create")
        self._set_build_method()

        if self.use_remote_state is True:
            self.create_remote_tf_bkend()  # use backend to track state file

        self.create_config0_settings_file()  # copy of settings file
        self._exec_tf(method="create")

        # we clean if local build
        if self.build_method == "local":
            cmd = "rm -rf {}/.terraform".format(self.exec_dir)  # clean up .terraform
            os.system(cmd)

        return self.tf_results

    def _set_tfstate_parse(self):

        if not self.tf_configs:
            return

        # new version of resource setttings
        resource_configs = self.tf_configs.get("resource_configs")

        if resource_configs and resource_configs.get("include_raw"):
            self.tf_exec_include_raw = True

        if resource_configs and resource_configs.get("include_keys"):
            self.tf_exec_add_keys = resource_configs["include_keys"]

        if resource_configs and resource_configs.get("exclude_keys"):
            self.tf_exec_remove_keys.extend(resource_configs["exclude_keys"])

        if resource_configs and resource_configs.get("map_keys"):
            self.tf_exec_map_keys = resource_configs["map_keys"]

    def run(self):

        if self.method == "create":
            self.create()
        elif self.method == "destroy":
            self.destroy()
        elif self.method == "validate":
            self.validate()
        else:
            usage()
            print('method "{}" not supported!'.format(self.method))
            exit(4)

    def create(self):

        self.init_phase_run()

        if self.phase == "submit":
            self._init_create()
            self._exec_tf_apply()
        elif self.phase == "retrieve":
            self._exec_tf_apply()
        else:
            self._init_create()
            self._exec_tf_apply()

        if self.tf_results and self.tf_results.get("output"):
            self.append_log(self.tf_results["output"])
            del self.tf_results["output"]

        if self._eval_post_tf("create"):
            return self._post_create()

        return

    def _init_create(self):

        if not self.stateful_id:
            self.logger.error("STATEFUL_ID needs to be set")

        # revisit 4352525
        if not self.templify(app_template_vars="TF_EXEC_TEMPLATE_VARS",
                             **self.inputargs):
            self.exclude_tfvars = self._create_terraform_tfvars()

        if not os.path.exists(self.exec_dir):
            failed_message = "terraform directory must exists at {} - something went wrong".format(self.exec_dir)
            raise Exception(failed_message)

    def _post_create(self):

        # it succeeds at this point
        # parse tfstate file
        os.chdir(self.exec_dir)
        self._set_tfstate_parse()

        if self.postscript_path:
            self.logger.debug("u4324: getting resource from custom postscript path")
            resource = self.get_resources_details()

            try:
                resource = self.to_json(resource)
            except:
                self.logger.warn("u4324: could not convert resource to json")

        else:
            self.logger.debug("u4324: getting resource from standard tfstate_to_output")

            resource = self._tfstate_to_output()

            if self.add_resource_inputargs:
                resource["resource_inputargs"] = self.add_resource_inputargs

            resource = self.configure_resources_details(resource)

        if not resource: 
            self.logger.warn("u4324: resource info is not found in the output")
            return

        os.chdir(self.cwd)

        # enter into resource db through
        # file location or through standard out
        self.write_resource_to_json_file(resource,
                                         must_exist=True)

        return True

    #####################################
    # move to separate DockerLocalBuild
    #####################################
    def _create_docker_env_file(self):

        # note: self.docker_env_file is set by
        # "_get_docker_env_filepath" in ResourceCmdHelper
        if not self.build_env_vars.items():
            return

        file_obj = open(self.docker_env_file,"w")

        for _k,_v in self.build_env_vars.items():
            file_obj.write("\n")
            file_obj.write("{}={}".format(_k,_v))

        file_obj.close()

    def _get_docker_run_cmd(self,**kwargs):

        share_dir = kwargs.get("share_dir",
                               self.share_dir)

        run_share_dir = kwargs.get("run_share_dir",
                                   self.run_share_dir)

        docker_env_file = kwargs.get("docker_env_file",
                                     self.docker_env_file)

        if not os.path.exists(docker_env_file):

            self.logger.error("Cannot find environmental file {}".format(docker_env_file))

            if self.method:
                cmd = 'docker run -e METHOD="{}" --rm -v {}:{} {}'.format(self.method,
                                                                          run_share_dir,
                                                                          share_dir,
                                                                          self.docker_image)
            else:
                cmd = 'docker run --rm -v {}:{} {}'.format(run_share_dir,
                                                           share_dir,
                                                           self.docker_image)
        else:
            if self.method:
                cmd = 'docker run -e METHOD="{}" --env-file {} --rm -v {}:{} {}'.format(self.method,
                                                                                        docker_env_file,
                                                                                        run_share_dir,
                                                                                        share_dir,
                                                                                        self.docker_image)
            else:
                cmd = 'docker run --env-file {} --rm -v {}:{} {}'.format(docker_env_file,
                                                                         run_share_dir,
                                                                         share_dir,
                                                                         self.docker_image)

        return cmd

    def _exec_docker_local(self,retries=None):

        os.chdir(self.run_share_dir)

        cmd = self._get_docker_run_cmd()

        self.logger.debug(cmd)

        if self.method == "destroy" and retries:
            retries = 6

        if not retries:
            retries = 1

        output = None

        for retry in range(retries):

            results = self.execute(cmd,
                                   output_to_json=False,
                                   exit_error=False)

            output = self._aggregate_output(results,
                                            output=output)

            if not results or results.get("status") is False:
                continue

            break

        results["output"] = output

        return results


    #####################################

def usage():

    print("""
script + environmental variables

basic:
    main environment variable
        CONFIG0_RESOURCE_SETTINGS - The resource settings are retrieved from the environment variable 
                                     CONFIG0_RESOURCE_SETTINGS_HASH, which is base64 encoded - this is sanitised
        METHOD - This needs to be set
        
    other environment variables
        TF_EXEC_TEMPLATE_VARS - environmental variables use for templating terraform files (not common)
       """)

if __name__ == '__main__':

    main = Main()

    # sets "config0_resource_settings_hash" in self.inputargs
    main.set_inputargs(set_env_vars=["CONFIG0_RESOURCE_SETTINGS_HASH"])
    main.run()
